.TH "setdasd" "8" "Mon Sep 23 2013" "md_monitor 5.3"
.de bu
.IP \(bu
..
.SH NAME
setdasd \- set or unset DASD device flags
.SH SYNOPSIS
.B setdasd
[\fI-t \fB0|1\fR|\fI--timeout=\fB0|1\fR]
[\fI-q \fB0|1\fR|\fI--quiesce=\fB0|1\fR]
[\fI-d \fBdevnode\fR|\fI--device=\fBdevnode\fR]
[\fI-s \fBdevpath\fR|\fI--sysfs=\fBdevpath\fR]
[\fI-p \fBprio\fR|\fI--log-priority=\fBprio\fR]
[\fI-v\fR|\fI--verbose\fR]
[\fI-h\fR|\fI--help\fR]
.SH DESCRIPTION
.PP
\fBsetdasd\fR is a program for setting or unsetting the internal DASD
device flags via ioctl. It currently supports setting the 'ABORTIO'
flag via 'BIODASDABORTIO' and 'BIODASDALLOWIO' ioctls, and setting
the 'QUIESCE' flag via 'BIODASDQUIESCE' and 'BIODASDRESUME' ioctls.

.SH OPTIONS
.PP
\fBsetdasd\fR recognizes the following command-line options:
.TP
\fI-t \fB0|1\fR, \fI--timeout=\fB0|1\fR
Set or unset the 'ABORTIO' flag.
.TP
\fI-q \fB0|1\fR, \fI--quiesce=\fB0|1\fR
Set or unset the 'QUIESCE' flag.
.TP
\fI-d \fIdevnode\fR, \fI--device=\fBdevnode\fR
Use the device specified by device node \fBdevnode\fR.
.TP
\fI-s \fIdevpath\fR, \fI--sysfs=\fBdevpath\fR
Use the device specified by sysfs path \fBdevpath\fR.
.TP
\fI-h\fR, \fI--help\fR
Display setdasd usage information.
.TP
\fI-p \fBprio\fR, \fI--log-priority=\fBprio\fR
Set logging priority to \fBprio\fR.
.TP
\fI-v\fR, \fI--verbose\fR
Increase logging priority

.SH SEE ALSO
.IR
md_monitor(8)
